### ISSUE TITLE
Missing output files

### ISSUE THREAD

**Issue by moldach** [ksablauskas/denovocnn#3]
The job 

1) There is no output file generated for `-o=testFile.vcf`?
2) The output directory (`-w=deNovoCNN_CG00010`) looks incomplete; however, the _expected_ output files are not listed in the [README}(https://github.com/ksablauskas/denovocnn) so it's impossible to be certain

## Script

```
#!/bin/bash
#BSUB -q normal
#BSUB -n 1
#BSUB -R "rusage[mem=10G]"
#BSUB -R "select[hname!=node013]"
#BSUB -M 10000
#BSUB -W 48:00
#BSUB -u moldach@ucalgary.ca
#BSUB -J freebayes_deNovoCNN
#BSUB -o freebayes_deNovoCNN.out
#BSUB -e freebayes_deNovoCNN.err

./predict.sh \
    -w=deNovoCNN_CG00010 \
    -cv=proband_freebayes_filt_normalized_decompose.vcf \
    -fv=dad_freebayes_filt_normalized_decompose.vcf \
    -mv=mom_freebayes_filt_normalized_decompose.vcf \
    -cb=proband_bwaMEM_sort_dedupped.bam \
    -fb=dad_bwaMEM_sort_dedupped.bam \
    -mb=mom_bwaMEM_sort_dedupped.bam \
    -sm=snp.h5 -im=insertions.h5 \
    -dm=deletions.h5 \
    -g=Homo_sapiens.GRCh37.dna.toplevel.fa \
    -o=testFile.vcf \
    -m=genome
```

### `.err`

```
Writing to /tmp/bcftools-sort.bOeRsz
Merging 2 temporary files
Cleaning
Done
Writing to /tmp/bcftools-sort.QSxOE8
Merging 3 temporary files
Cleaning
Done
Writing to /tmp/bcftools-sort.GA35Ba
Merging 4 temporary files
Cleaning
Done
Note: -w option not given, printing list of sites...
```

### `.out`

```
Successfully completed.

Resource usage summary:

    CPU time :                                   360.86 sec.
    Max Memory :                                 880 MB
    Average Memory :                             258.70 MB
    Total Requested Memory :                     10240.00 MB
    Delta Memory :                               9360.00 MB
    Max Swap :                                   -
    Max Processes :                              5
    Max Threads :                                6
    Run time :                                   360 sec.
    Turnaround time :                            354 sec.

The output (if any) follows:

Start preprocessing step
Preprocessing step finished
Generated jobs for slurm in:
deNovoCNN_CG00010/jobs


PS:

Read file <freebayes_deNovoCNN.err> for stderr output of this job.
```

## Output directory

```
(base) [moldach@synergy bwa]$ ll deNovoCNN_CG00010/
total 4480
-rw-r--r-- 1 moldach mtgraovac  231070 Oct 22 10:17 intersected_part00.txt
-rw-r--r-- 1 moldach mtgraovac  214559 Oct 22 10:17 intersected_part01.txt
-rw-r--r-- 1 moldach mtgraovac  215369 Oct 22 10:17 intersected_part02.txt
-rw-r--r-- 1 moldach mtgraovac  210892 Oct 22 10:17 intersected_part03.txt
-rw-r--r-- 1 moldach mtgraovac  210734 Oct 22 10:17 intersected_part04.txt
-rw-r--r-- 1 moldach mtgraovac  206963 Oct 22 10:17 intersected_part05.txt
-rw-r--r-- 1 moldach mtgraovac  207619 Oct 22 10:17 intersected_part06.txt
-rw-r--r-- 1 moldach mtgraovac  206091 Oct 22 10:17 intersected_part07.txt
-rw-r--r-- 1 moldach mtgraovac  219167 Oct 22 10:17 intersected_part08.txt
-rw-r--r-- 1 moldach mtgraovac   48346 Oct 22 10:17 intersected_part09.txt
-rw-r--r-- 1 moldach mtgraovac 1970810 Oct 22 10:17 intersected.txt
drwxr-xr-x 2 moldach mtgraovac    4096 Oct 22 10:18 jobs
drwxr-xr-x 2 moldach mtgraovac    4096 Oct 22 10:17 logs
```

**Comment by moldach** [comment]
I looked inside the `jobs` folder and saw that these `.txt` files are actually `SLURM` scripts.

I adapted it for a `LSF` scheduler and submitted but I get this error:

## `jobs/job_intersected_part00.txt`

```
#!/bin/bash

#BSUB -J intersected_part00
#BSUB -W 02:00
#BSUB -n 16
#BSUB -M 16100
#BSUB -o PREDICT_intersected_part00.out
#BSUB -e PREDICT_intersected_part00.err

# export PATH=/path/to/env
source ~/bin/denovocnn/bin/activate

KERAS_BACKEND=tensorflow python ./main.py \
    --mode=predict \
    --genome=/tiered/mtgraovac/indexes/GRCh37/Homo_sapiens.GRCh37.dna.toplevel.fa \
    --child-bam=proband_bwaMEM_sort_dedupped.bam \
    --father-bam=dad_bwaMEM_sort_dedupped.bam \
    --mother-bam=mom_bwaMEM_sort_dedupped.bam \
    --snp-model=snp.h5 \
    --in-model=insertions.h5 \
    --del-model=deletions.h5 \
    --intersected=testMonday/intersected_part00.txt \
    --output=testFile.vcf_intersected_part00.txt
```

## Log

```
2020-10-26 14:59:31.509525: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "./main.py", line 99, in <module>
    dnms_table = infer_dnms_from_intersected(path_to_tsv, child_bam, father_bam, mother_bam, REREFERENCE_GENOME, snp_model, in_model, del_model)
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/infer.py", line 120, in infer_dnms_from_intersected
    model_snps.load_weights(snp_model)
  File "/home/moldach/bin/denovocnn/lib/python3.5/site-packages/keras/engine/network.py", line 1161, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/moldach/bin/denovocnn/lib/python3.5/site-packages/keras/engine/saving.py", line 900, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 6 layers into a model with 19 layers.
```

**Comment by moldach** [comment]
Any idea why I'm getting this error about weights/models?

I found this [issue on `keras`](https://github.com/keras-team/keras/issues/10417) which seemed to suggest downgrading to `keras` version `2.1.6` would solve the problem but it didn't work for me.

**Comment by gelana** [comment]
Hi @moldach, 
Could you please update the model files (sibstitutions, insertions, deletions) you're using to run the tool?

**Comment by moldach** [comment]
Hi @gelana after updating the new model files I get a new error:

```
Using TensorFlow backend.
2020-11-06 15:07:57.802231: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "./main.py", line 99, in <module>
    dnms_table = infer_dnms_from_intersected(path_to_tsv, child_bam, father_bam, mother_bam, REREFERENCE_GENOME, snp_model, in_model, del_model)
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/infer.py", line 131, in infer_dnms_from_intersected
    splitted_intersected_array = split_comma_separated_variants(intersected_dataframe)
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/infer.py", line 84, in split_comma_separated_variants
    chromosome = check_chromosome(chromosome)
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/infer.py", line 73, in check_chromosome
    raise Exception('Wrong chromosome:', chromosome)
Exception: ('Wrong chromosome:', 'HG1287_PATCH')
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2aabc59d18d0>>
Traceback (most recent call last):
  File "/home/moldach/bin/denovocnn/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 686, in __del__
TypeError: 'NoneType' object is not callable
```

Looks like the error might stem from `Exception: ('Wrong chromosome:', 'HG1287_PATCH')`.

**Comment by gelana** [comment]
@moldach we expect the chromosome be in format chr1, chr2, ... or 1, 2, ... here we see HG1287_PATCH. 
could you please show the first rows of testMonday/intersected_part00.txt file?

**Comment by moldach** [comment]
Hi @gelana.

[Heng Li wrote about the issues of using different reference genomes here](https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use) so this seems to be an issue with the inclusion of ALT/patch contigs.

The first few lines of `intersected_part00.txt` file:

```
G1287_PATCH    143873261       T       C       100
HG1287_PATCH    143873417       C       T       100
HG1287_PATCH    143873450       T       G       100
```

So i tried to subset this to make a file with only chromosome `1` inside via:

```
awk '$1 == "1" { print }' intersected_part00.txt > subset_part00.txt
```

So this file looks like (_dummy data_):

```
1       102413   A       AC      100
1       15238   A       G       100
```

I try to re-run the script:

```
KERAS_BACKEND=tensorflow python ./main.py \
    --mode=predict \
    --genome=/tiered/mtgraovac/indexes/GRCh37/Homo_sapiens.GRCh37.dna.toplevel.fa \
    --child-bam=deNOVOCNN/proband_trim_bwaMEM_sort_dedupped_recalib.bam \
    --father-bam=deNOVOCNN/dad_trim_bwaMEM_sort_dedupped_recalib.bam \
    --mother-bam=deNOVOCNN/mom_trim_bwaMEM_sort_dedupped_recalib.bam \
    --snp-model=snp.advanced_model.45.h5 \
    --in-model=insertions.advanced_model.45.h5 \
    --del-model=deletions.advanced_model.45.h5 \
    --intersected=subset_part00.txt \
    --output=testFile.vcf_intersected_part00.txt


### New error

The log now says:

> ValueError: invalid contig `chr1`

```
2020-11-10 10:49:09.380658: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "./main.py", line 99, in <module>
    dnms_table = infer_dnms_from_intersected(path_to_tsv, child_bam, father_bam, mother_bam, REREFERENCE_GENOME, snp_model, in_model, del_model)
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/infer.py", line 154, in infer_dnms_from_intersected
    child_variant = SingleVariant(str(chromosome), int(start), int(end)+1, child_bam, REREFERENCE_GENOME)
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/variants.py", line 53, in __init__
    self.encode_pileup()
  File "/gpfs/home/moldach/projects/saliva/ensembl/bwa-trio/alignment/bwa/denovonet/variants.py", line 94, in encode_pileup
    for idx, read in enumerate(self.bam_data.fetch(reference=self.chromosome, start=self.start, end=self.end)):
  File "pysam/libcalignmentfile.pyx", line 1082, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `chr1`
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x2aab4e7d0780>>
Traceback (most recent call last):
  File "/home/moldach/bin/denovocnn/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 686, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by moldach** [comment]
## Questions

1. Can you please provide information on which genome reference you trained the model(s) on?

2. Additionally, would the model be tightly coupled with any _specific_ reference genome?

Using `Ensembl`'s `GRCh37` `topLevel` reference (`Homo_sapiens.GRCh37.dna.toplevel.fa`) so chromosomes are in format `1`, `2`, `...`.

3. How does `deNovoCNN` handle strings for chromosome X and MtDNA?

**Comment by moldach** [comment]
Eager to hear back about these questions

**Comment by rahit** [comment]
Having the same issue. Any update?
